wandb_version: 1

model:
  desc: null
  value: gpt-4-0125-preview
dataset:
  desc: null
  value: task_anachronisms
shot:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706808598.987326
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 16
      - 23
      4: 3.12.1
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
