wandb_version: 1

name:
  desc: null
  value: Baseline [datasets/task_logical_sequence.json]
system_prompt:
  desc: null
  value: Identify the correct chronological or sequential order of items in a list.
model:
  desc: null
  value: gpt-3.5-turbo-0125
shots:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706883312.691261
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 16
      - 23
      4: 3.12.1
      5: 0.16.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
